### ISSUE TITLE
Rerun keepup on run3 with new icaruscode version

### ISSUE THREAD

**Issue by mt82** [SBNSoftware/icarus-production#17]
Likely everyone is aware that we had a fhicl file mismatch for the keep up processing which meant we were not doing any tracking. 
@icaromx corrected the fhicl files last week so the problem should be fixed going forward... but **we are now faced with the need to reprocess all run 3 data..**.. since nobody has looked at run 3 reconstruction until now I assumed we would wait until later in the Summer and set up then to do this. But this morning's analysis meeting indicated a desire to get it all redone ASAP.... Hopefully we can pair that back to a few specific runs for the short term but we probably need to think about how we can handle that. Perhaps I am wrong, but I assume Run 3 raw data has not been preserved on disk or has it been?

**Comment by mt82** [comment]
icaruscode v09_90_00 and stage1 fcl file to `stage1_run2_1d_icarus.fcl`

**Comment by PetrilloAtWork** [comment]
@SFBayLaser suggested `stage0_run2_icarus.fcl` and `stage1_run2_1d_larcv_icarus.fcl` with `v09_90_00` (for requests `#13` and `#14`, that is issues #2 and #3).

**Comment by SFBayLaser** [comment]
We might not need to produce larcv output, I would query the ML group. If we don't need to produce larcv output during keep up then we could use the stage 1 file Matteo referenced above.

**Comment by mt82** [comment]
from @icaromx 
Hi Minerba,

 

The reprocessing of Run3 has started. We switched to icaruscode v09_90_00 and are using stage1_run2_1d_icarus.fcl for the stage1 processing in the keepup. The files should be available here:

 

    Stage1 files: /pnfs/icarus/scratch/users/icaruspro/dropbox/data/poms_production/icarus_keepup/v09_90_00/alldatastreams/stage1/
    Calibtuples: /pnfs/sbn/data/sbn_fd/poms_production/data/Run3/reconstructed/icaruscode_v09_90_00/alldatastreams/calibtuples/
    flatcafs: /pnfs/sbn/data/sbn_fd/poms_production/data/Run3/reconstructed/icaruscode_v09_90_00/alldatastreams/flatcaf_*/

 

Files from more recent runs (above 11973) should be available and earlier runs are in queue to be reprocessed.

 

--Ivan

**Comment by francois-drielsma** [comment]
Hi everyone, I am aware I have missed the train on this one but I was told by Gianluca I should comment nonetheless for posterity that we do indeed need LArCV files to be produced as part of keep up processing. I am not sure where we landed on this in the end but if no LArCV files were produced and the files are reprocessed at some point, they should be made then to enable the use of the SPINE reconstruction package.
