### ISSUE TITLE
Run a test campaign

### ISSUE THREAD

**Issue by mt82** [SBNSoftware/icarus-production#18]
from @mattfcs 
How to set a campaign to run over a set number of files from a dataset:

1. Go to the Campaign Editor GUI
2. Select the initial stage, then param_overrides
3. On the Param Editor, click on any + and add: `-Osubmit.N=` on the left and the number of files on the right (I suggest ~10)
4. Save it, and run

This is the same way we set tests to run only a few files (you can check it in the test_param_overrides). Unfortunately this is not super reliable, sometimes POMS ignores it for different reasons. @PromitaRoy had this issue with tests not long ago, so I recommend to always make sure how many files were submitted once you try to run a test.

In case the above setup does not work, here is a more brute force way to do it:

1. Go to the Campaign Editor GUI
2. Select the initial stage and "Edit" on cs_split_type
3. On "Base Split Type" select `nfiles` then fill `n:`  with the number of files you want (I suggest ~10)
4. Save it, and run (if needed to run over the full sample, just change "Base Split Type" back to `none`)

**Comment by mt82** [comment]
Create new cfg files starting from the one @PromitaRoy is using and fix the name of the input and output files.

**Comment by PromitaRoy** [comment]
Did the necessary changes on the test campaign  for Francisco. The campaign should run smoothly without any input/output file mismatch error.
